name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 60  # Ajustado a 60 minutos (ajusta según tus necesidades)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Playwright
        run: npm install -D playwright

      - name: Download Downloads.bat with Playwright
        run: |
          $context = New-PlaywrightContext -Browser Chromium
          $page = $context.NewPage()

          $page.Goto("https://gitlab.com/chamod2/lm_win-10_github_rdp/-/raw/main/Downloads.bat")

          # Resolver el captcha manualmente (o usar un servicio de resolución de captchas)

          $page.WaitForDownload() | Receive-Job -Wait -AutoRemoveJob
          $download = $page.GetDownloads() | Select-Object -First 1
          $download.SaveAs("./Downloads.bat")

          $context.Close()

      - name: Connect to LiteManager
        run: echo "Conectando a LiteManager..." # Reemplazar con el comando real para conectar a LiteManager

      - name: Time Counter
        run: cmd /c loop.bat
